### ISSUE TITLE
How do I generate a x2 upscale tflite model?

### ISSUE THREAD

**Issue by kevinkkk0321** [Algolzw/NCNet#7]
Hi @Algolzw , thanks for your great work.

I saw that the pretrained models are all upscaling x3, I would like to know if it's possible to generate x2 tflite model?
Since I use the generate_tflite.py and **change the scale_factor from 3 to 2**, but still got a x3 upscaling model. 
Any instruction?  Thanks a lot!

**Comment by Algolzw** [comment]
Hi! You can directly change the scale to x2 in the [main.py](https://github.com/Algolzw/NCNet/blob/048486534a209c72ef6bbe991a4a926e61c18345/main.py#L9) and retrain the model.

**Comment by kevinkkk0321** [comment]
Got it! I'll try it, thanks!
